version: '3.4'

volumes:
  jizhang-mysql:
    name: jizhang-mysql
  jizhang-redis:
    name: jizhang-redis

services:
  mysql:
    build:
      context: ./mysql/
    volumes:
      - jizhang-mysql:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${JIZHANG_DB_PASSWORD}
  redis:
    build:
      context: ./redis/
    ports:
      - "10087:6379"
    volumes:
      - jizhang-redis:/data
  api:
    build:
      context: ./server-side/build/
    ports:
      - "${JIZHANG_SERVER_SIDE_PORT}:44444"
    environment:
      LANG: C.UTF-8
      SERVER_PORT: 44444
      JIZHANG_DB_HOST: mysql
      JIZHANG_DB_NAME: jizhang
      JIZHANG_DB_USER: root
      JIZHANG_CACHE_PORT: 6379
      JIZHANG_CACHE_HOST: redis
      JIZHANG_DB_PASSWORD: ${JIZHANG_DB_PASSWORD}
      JIZHANG_REDIS_URL: redis
    depends_on:
      - mysql
      - redis
  ui:
    build: ./front-end/build/
    ports:
      - "${JIZHANG_FE_PORT}:80"
    depends_on:
      - api